# Generated by Django 5.0.6 on 2024-05-22 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pereval_ID', '0002_remove_level_autumn_lv_remove_level_spring_lv_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='autumn_lev',
            new_name='autumn_lv',
        ),
        migrations.RenameField(
            model_name='level',
            old_name='spring_lev',
            new_name='spring_lv',
        ),
        migrations.RenameField(
            model_name='level',
            old_name='summer_lev',
            new_name='summer_lv',
        ),
        migrations.RenameField(
            model_name='level',
            old_name='winter_lev',
            new_name='winter_lv',
        ),
    ]
