# Generated by Django 5.0.6 on 2024-05-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pereval_ID', '0003_rename_autumn_lev_level_autumn_lv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='autumn_lv',
        ),
        migrations.RemoveField(
            model_name='level',
            name='spring_lv',
        ),
        migrations.RemoveField(
            model_name='level',
            name='summer_lv',
        ),
        migrations.RemoveField(
            model_name='level',
            name='winter_lv',
        ),
        migrations.AddField(
            model_name='level',
            name='autumn',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('3A', '3A'), ('4A', '4A')], default='1A', max_length=2),
        ),
        migrations.AddField(
            model_name='level',
            name='spring',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('3A', '3A'), ('4A', '4A')], default='1A', max_length=2),
        ),
        migrations.AddField(
            model_name='level',
            name='summer',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('3A', '3A'), ('4A', '4A')], default='1A', max_length=2),
        ),
        migrations.AddField(
            model_name='level',
            name='winter',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('3A', '3A'), ('4A', '4A')], default='1A', max_length=2),
        ),
        migrations.AlterField(
            model_name='pereval_added',
            name='status',
            field=models.CharField(choices=[('new', 'новый'), ('pending', 'в работе'), ('accepted', 'принято'), ('rejected', 'отклонено')], default='new', max_length=10),
        ),
    ]
