# Generated by Django 5.0.6 on 2024-05-27 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pereval_ID', '0005_alter_level_autumn_alter_level_spring_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coords',
            options={'verbose_name': 'Координаты', 'verbose_name_plural': 'Координаты'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображение'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name': 'Уровень сложности', 'verbose_name_plural': 'Уровни сложности'},
        ),
        migrations.AlterModelOptions(
            name='pereval_added',
            options={'verbose_name': 'Перевал', 'verbose_name_plural': 'Перевалы'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Турист', 'verbose_name_plural': 'Туристы'},
        ),
        migrations.AlterField(
            model_name='coords',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='coords',
            name='latitude',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='coords',
            name='longitude',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='images',
            name='pereval_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Pereval_ID.pereval_added'),
        ),
        migrations.AlterField(
            model_name='level',
            name='autumn',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Осень'),
        ),
        migrations.AlterField(
            model_name='level',
            name='spring',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Весна'),
        ),
        migrations.AlterField(
            model_name='level',
            name='summer',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Лето'),
        ),
        migrations.AlterField(
            model_name='level',
            name='winter',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Зима'),
        ),
        migrations.AlterField(
            model_name='pereval_added',
            name='beauty_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название препятствия'),
        ),
        migrations.AlterField(
            model_name='pereval_added',
            name='connect',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pereval_added',
            name='coord_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pereval_ID.coords'),
        ),
        migrations.AlterField(
            model_name='pereval_added',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pereval_ID.level'),
        ),
        migrations.AlterField(
            model_name='pereval_added',
            name='other_titles',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Другое название'),
        ),
        migrations.AlterField(
            model_name='pereval_added',
            name='status',
            field=models.CharField(choices=[('new', 'новый'), ('pending', 'модератор взял в работу'), ('accepted', 'модерация прошла успешно'), ('rejected', 'модерация прошла, информация не принята')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='pereval_added',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название вершины'),
        ),
        migrations.AlterField(
            model_name='pereval_added',
            name='tourist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourist_id', to='Pereval_ID.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='users',
            name='fam',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='otc',
            field=models.CharField(max_length=255, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Номер телефона'),
        ),
    ]
